services:
  devops:
    build: .
    image: devops:latest
    restart: always
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/iwvgdevopsdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - devopsNet

networks:
  devopsNet:
    name: devopsNet
    external: true

#> docker compose up --build -d