server:
  port: 10000
app:
  hosting: AWS

logging:
  level:
    root: WARN
    es.upm.miw: INFO
spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/iwvgdevopsdb_vdxx
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

management:
  endpoint:
    health:
      show-details: always
