server:
  port: 10000

app:
  hosting: AWS

logging:
  level:
    root: WARN
    es.upm.miw: INFO

spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/iwvgdevopsdb_vdxx}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver