name: CD - BBDD
on:
  push:
    branches: ['main']

jobs:
  cd:
    name: Deploy PostgreSQL on AWS Lightsail
    runs-on: ubuntu-22.04
    steps:
      - name: 🐳 Deploy PostgreSQL on AWS Lightsail
        uses: appleboy/ssh-action@8faa84277b88b6cd1455986f459aa66cf72bc8a3
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP_MAIN }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER_MAIN }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY_MAIN }}
          script: |
            docker network inspect devopsNet >/dev/null 2>&1 || docker network create devopsNet
            docker pull postgres:15.10
            docker rm -f postgres || true
            docker run -d \
              --name postgres \
              --restart always \
              --network devopsNet \
              -e POSTGRES_DB=iwvgdevopsdb_vdxx \
              -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
              -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
              --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }} -d iwvgdevopsdb_vdxx" \
              --health-interval=10s \
              --health-timeout=5s \
              --health-retries=5 \
              -v postgres-data:/var/lib/postgresql/data \
              postgres:15.10
            
            echo "⏳ Esperando a que se levante"
            for i in $(seq 1 6); do
              sleep 15
              STATUS=$(docker inspect --format='{{.State.Health.Status}}' postgres 2>/dev/null)
              echo "Intento $i: $STATUS"
              [ "$STATUS" = "healthy" ] && break
            done
            
            if [ "$STATUS" != "healthy" ]; then
              echo "❌ Deploy fallido"
              docker logs --tail 50 postgres
              exit 1
            fi
            
            echo "✅ Deploy exitoso"
            docker image prune --filter "until=12h" -f